### PR TITLE
Added Bootstrap 3 stylesheet

### PR DESCRIPTION
**Pull request by maurotrigo**
I simply added the Bootstrap 3 stylesheet from http://www.eyecon.ro/bootstrap-datepicker/.

### CODE REVIEW

**Comment by maurotrigo** [comment]
Anybody home?

**Comment by AlphaGit** [comment]
ping @andresmoschini

**Comment by AlphaGit** [comment]
@andresmoschini If you don't have the time to take a look at this, please let me know who would be most appropriate to. I could go into it but my experience with this particular product is very limited. Still, I offer myself if you think I could help.

As a side note let's get together next week to discuss about the other open PRs and address if something needs to be done with them.

**Comment by andresmoschini** [comment]
Thanks @maurotrigo and @AlphaGit, I will check this and if I cannot pay attention to the PRs I will try to find someone.

**Comment by maurotrigo** [comment]
Thanks @andresmoschini, let me know if I can help!

**Comment by andresmoschini** [comment]
Well, It could be great if you update demo page and dependencies to use
Bootstrap 3 and your style sheet.

**Comment by maurotrigo** [comment]
Alright, I'm working on it.

**Comment by maurotrigo** [comment]
Ok, everything seems to be working alright. I realized there was a lot more work to be done, I had to make several changes to the Bootstrap 3 css so that all cases are supported on the demo page. Please take a quick look at the results.

**Comment by andresmoschini** [comment]
Really nice work @maurotrigo! Thanks for your help.
Merging...

**Comment by maurotrigo** [comment]
Awesome!

**Pull request merged**
